minmath/solve/urls.py
from django.urls import path

from . import views

app_name = "solve"

urlpatterns = [
    path("", views.landing, name = "landing"),
    path("game", views.game, name = "game"),
    path("info", views.info, name = "info"),
    path("submit_score", views.submit_score, name = "submit_score"),
    path("results", views.results, name = "results"),
]

minmath/solve/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from account.models import PlayerUser

# Create your models here.
# Models being akin to database tables

class Minigame(models.Model):
    # Model for each minigame session with end score and time
    # Used for leaderboards, tied to user
    # Leaderboards: username, gamemode, score, time, total num of problems, date
    user = models.ForeignKey(PlayerUser, on_delete=models.CASCADE) # on deletion of obj, delete those references that depend on it; one-to-many foreignkey
    score = models.IntegerField()
    time_duration = models.IntegerField()
    date = models.DateTimeField(auto_now=True); # for activity records

    def __str__(self):
        return (f"{self.user}'s {self.score}-score {self.time_duration}-second game on {self.date}")

minmath/solve/forms.py
from django import forms
from .models import Minigame

class MinigameForm(forms.ModelForm):
    class Meta:
        model = Minigame
        fields = ["score", "time_duration"]

minmath/solve/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse, HttpResponseNotAllowed
from .models import Minigame
from .forms import MinigameForm
from django.contrib.auth.decorators import login_required
from django.urls import reverse

# Create your views here.

def landing(request):
    return render(request, "solve/landing.html")

def game(request):
    return render(request, "solve/game.html")

def results(request):
    score = request.session.pop("score", None)
    return render(request, "solve/results.html", {"score": f"Score: {score}"})

def info(request):
    return render(request, "solve/info.html")

def submit_score(request):
    score = None
    if request.method == "POST":
        form = MinigameForm(request.POST)
        if form.is_valid():
            score = form.cleaned_data.get("score")
            if request.user.is_authenticated:
                game = form.save(commit=False)
                game.user = request.user
                game.save()
                print("SUCCESS:", game)
            request.session["score"] = score
        return redirect(reverse("solve:results"))
    return redirect(reverse("solve:results"))

minmath/solve/templates/solve/game.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>minmath - game</title>
{% endblock title %}

{% block content %}
<div id = "display-wrapper">
    <div id = "session" class = "gamebox">
        <div id = "math"></div>
        <input id = "math-input" tabindex = "1" autocomplete = "off"/>
        <div id = "track">
            <div id = "input-status"></div>
            <div id = "score" class = "gameinfo">Score: 0</div>
            <div id = "mode-status" class = "gameinfo"></div>
        </div>
        <div id = "progress-bar"></div>
    </div>
    <form id = "score-form" method = "post" action = "{% url 'solve:submit_score' %}">
        {% csrf_token %}
        <input type = "hidden" id = "time-submission" name = "time_duration" value = "0">
        <input type = "hidden" id = "score-submission" name = "score" value = "0">
    </form>
    
</div>
{% endblock content %}

{% block scripts %}
<script src = "{% static 'game-load.js' %}"></script>
<script src = "{% static 'input-validation.js' %}"></script>
<script type = "module" src = "{% static 'problem-gen.js' %}"></script>
<script type = "module" src = "{% static 'answer-check.js' %}"></script>
{% endblock scripts %}

minmath/solve/templates/solve/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div id = "session">
    <div id = "math"></div>
    <input id = "math-input"/>
    <div id = "track">
        <div id = "input-status"></div>
        <div id = "score">Score: 0</div>
    </div>
</div>
{% endblock content %}

{% block scripts %}
<script src = "{% static 'focus.js' %}"></script>
<script type = "module" src = "{% static 'problem_generator.js' %}"></script>
<script type = "module" src = "{% static 'answer_check.js' %}"></script>
<script src = "{% static 'mode_select.js' %}"></script>
{% endblock scripts %}

minmath/solve/templates/solve/info.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>minmath - info</title>
{% endblock title %}

{% block content %}
<div class = "about">
    <p>
        Minmath is a minimalist mental math website.
    </p>
</div>
{% endblock content %}

minmath/solve/templates/solve/landing.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class = "about">
    {% if user.is_authenticated %}
    Welcome back, {{user.username}}! 
    {% else %}
    Welcome to minmath - a minimalist mental math game.
    {% endif %}
    <br>
    Challenge yourself to solve as many problems as you can!
</div>

<div class = "mode-wrapper">
    <div id = "first" class = "mode-bar">
        <button id = "add" class = "mode-button md1" onclick = "modeParse(this.id)">add</button>
        <button id = "sub" class = "mode-button md1" onclick = "modeParse(this.id)">subtract</button>
        <button id = "mult" class = "mode-button md1" onclick = "modeParse(this.id)">multiply</button>
        <button id = "divd" class = "mode-button md1" onclick = "modeParse(this.id)">divide</button>
        <div class = "mode-button separator">|</div>
        <button id = "timed" class = "mode-button md2" onclick = "modeParse(this.id)">timed</button>
        <button id = "norm" class = "mode-button md2" onclick = "modeParse(this.id)">endless</button>
    </div>
    <div id = "second">
        <span id = "bounds" class = "mode-bar">
            <input class = "custom-input range" autocomplete = "off">
            to
            <input class = "custom-input range" autocomplete = "off">
            <div class = "mode-button separator">|</div>
            <input class = "custom-input range" autocomplete = "off">
            to
            <input class = "custom-input range" autocomplete = "off">
        </span>
        <span class = "mode-bar">
            <div>duration:</div>
            <select id = "duration" class = "mode-button" onchange = "selectTime(this.value)">
                <option value="15">15</option>
                <option value="30">30</option>
                <option value="60">60</option>
                <option value="90">90</option>
                <option value="120">120</option>
                <option hidden value="inf">∞</option>
            </select>
        </span>
    </div>
</div>

<a class = "start-button" href = "{% url 'solve:game' %}">start</a>
{% endblock content %}

{% block scripts %}
<script src = "{% static 'mode-select.js' %}"></script>
<script src = "{% static 'input-validation.js' %}"></script>
{% endblock scripts %}

minmath/solve/templates/solve/results.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>minmath - results</title>
{% endblock title %}

{% block content %}
<div id = "results" class = "gamebox">
    <div id = "performance" class = "gameinfo">{{score}}</div>
    <!--
    {% if not user.is_authenticated %}
        <span class="unauth-score-msg">(log in to save)</span>
    {% endif %}
    -->
    <a id = "restart" class = "menu-button" aria-label = "retry" href = "{% url 'solve:game' %}">
        <img class = "icon" src = "{% static 'icons/restartalt.svg' %}">
    </a>
</div> 
{% endblock content %}

{% block scripts %}
{% endblock scripts %}