minmath/account/urls.py
from django.urls import path
from . import views

app_name = "account"

urlpatterns = [
    path("", views.profile, name = "profile"),
    path("register/", views.register, name = "register"),
    path("profile/", views.profile, name = "profile"),
    path("logout/", views.logout_view, name = "logout"),
    path("login/", views.signin, name = "login"),
    path("api/recent-games/", views.recent_games, name = "recent_games")
]

minmath/leaderboards/urls.py
from django.urls import path
from . import views

app_name = "leaderboards"

urlpatterns = [
    path("", views.leaderboards, name = "leaderboards"),
]

minmath/solve/urls.py
from django.urls import path

from . import views

app_name = "solve"

urlpatterns = [
    path("", views.landing, name = "landing"),
    path("game", views.game, name = "game"),
    path("info", views.info, name = "info"),
    path("submit_score", views.submit_score, name = "submit_score"),
    path("results", views.results, name = "results"),
]

minmath/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
	<head>
        {% block title %}
		<title>minmath</title>
        {% endblock title %}
		<link rel = "stylesheet" type = "text/css" href = "{% static 'main.css' %}">
		<meta charset = "UTF-8">
        <meta name = "viewport" content = "width = device-width, initial-scale = 1">
	</head>
	<body>
        <div id = "container">
                <div id = "menu">
                    <a id = "name-header" class = "menu-button" href = "{% url 'solve:landing' %}">minmath</a>
                    <div id = "submenu">
                        <a id = "leaderboards" class = "menu-button" href = "{% url 'leaderboards:leaderboards' %}">
                            <img class = "icon" src = "{% static 'icons/leaderboard.svg' %}">
                        </a>
                        <a id = "info" class = "menu-button" href = "{% url 'solve:info' %}">
                            <img class = "icon" src = "{% static 'icons/info.svg' %}">
                        </a>
                        {% block profile %}
                        {% if user.is_authenticated %}
                        <a id = "account" class = "menu-button logx-button" href = "{% url 'account:profile' %}">
                            <img class = "icon" src = "{% static 'icons/account.svg' %}">
                        </a>
                        <a class = "menu-button logx-button" href = "{% url 'account:logout' %}">
                            <img class = "icon" src = "{% static 'icons/logout.svg' %}">
                        </a>
                        {% else %}
                        <a class = "menu-button logx-button" href = "{% url 'account:login' %}">
                            <img class = "icon" src = "{% static 'icons/login.svg' %}">
                        </a>
                        {% endif %}
                        {% endblock profile %}
                    </div>
                </div>
                <div id = "intro">
                    <div id = "mid">
                    {% block content %}
                    {% endblock content %}
                    </div>
                </div>
                <a href = "https://github.com/m-lm/minmath">
                    <img src = "{% static 'icons/github-mark.svg' %}" id = "footer">
                </a>
        </div>
    <script src = "{% static 'intro.js' %}"></script>
    {% block scripts %}
    {% endblock scripts %}
	</body>
</html>